# Generated by Django 4.1.7 on 2024-05-06 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_uso_actual', models.IntegerField(blank=True, null=True)),
                ('tiempo_adicionado', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('observations', models.TextField(max_length=1020)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente_id', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('EMOVIL', 'Equipo Movil'), ('TRANSPORTE', 'Transporte')], max_length=50)),
                ('serial', models.CharField(max_length=50)),
                ('marca_modelo', models.CharField(max_length=50)),
                ('kilometraje', models.IntegerField(blank=True, null=True)),
                ('tiempo_uso', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_priority', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formus.form')),
            ],
        ),
        migrations.CreateModel(
            name='FormImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/formus/')),
                ('completed_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='formus.completedform')),
            ],
        ),
        migrations.AddField(
            model_name='completedform',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formus.form'),
        ),
        migrations.AddField(
            model_name='completedform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completedform',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formus.vehiculo'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], max_length=2)),
                ('completed_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formus.completedform')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formus.question')),
            ],
        ),
    ]
