# Generated by Django 4.1.7 on 2024-05-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tiempo_uso',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
