# Generated by Django 4.1.7 on 2024-05-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formus', '0002_alter_vehiculo_tiempo_uso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tiempo_uso',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
