# Generated by Django 4.1.7 on 2024-05-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formus', '0003_alter_vehiculo_kilometraje_alter_vehiculo_tiempo_uso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tiempo_uso',
            field=models.IntegerField(default=0),
        ),
    ]
