# Generated by Django 4.1.7 on 2024-05-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formus', '0004_alter_vehiculo_tiempo_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='operativo',
            field=models.BooleanField(default=True),
        ),
    ]
