# Generated by Django 4.1.7 on 2024-05-20 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formus', '0005_vehiculo_operativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('OK', 'OK'), ('NOK', 'No OK'), ('REG', 'Regular')], max_length=3)),
                ('fecha_revision', models.DateField()),
                ('regularidad', models.IntegerField(help_text='Días hasta la próxima revisión')),
                ('observaciones', models.TextField(blank=True, max_length=1020, null=True)),
                ('imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formus.formimage')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formus.vehiculo')),
            ],
        ),
    ]
