# Generated by Django 4.1.7 on 2024-05-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formus', '0006_mantenimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mantenimiento',
        ),
    ]
