# Generated by Django 4.1.5 on 2023-01-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="modulo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M0", "Modulo 0"),
                    ("M1", "Modulo 1"),
                    ("M2", "Modulo 2"),
                    ("M3", "Modulo 3"),
                    ("M4", "Modulo 4"),
                    ("M5", "Modulo 5"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
