# Generated by Django 4.1 on 2023-02-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="location",
            field=models.CharField(
                choices=[
                    ("M0", "Modulo 0"),
                    ("M1", "Modulo 1"),
                    ("M2", "Modulo 2"),
                    ("M3", "Modulo 3"),
                    ("M4", "Modulo 4"),
                    ("M5", "Modulo 5"),
                    ("CF1", "Corta Fuego 1"),
                    ("CF2", "Corta Fuego 2"),
                    ("CF3", "Corta Fuego 3"),
                    ("CF4", "Corta Fuego 4"),
                    ("CF5", "Corta Fuego 5"),
                ],
                max_length=3,
            ),
        ),
    ]
