# Generated by Django 4.1.7 on 2023-03-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_cryptoprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tarea',
            field=models.CharField(choices=[('Sop', 'Soplado'), ('Asp', 'Aspirado'), ('Lav', 'Lavado')], default=None, max_length=3),
        ),
    ]
