# Generated by Django 4.1.7 on 2023-10-03 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_rack', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SwitchDeDistribucion',
            fields=[
                ('nro_swd', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('ip', models.GenericIPAddressField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='historialejecucionswd',
            name='num_switch',
        ),
        migrations.CreateModel(
            name='SwitchDeAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portchannel', models.IntegerField()),
                ('nro_swa', models.IntegerField()),
                ('nro_rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.rack')),
            ],
        ),
        migrations.AddField(
            model_name='rack',
            name='nro_swd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.switchdedistribucion'),
        ),
        migrations.CreateModel(
            name='HistorialEjecucionSWA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=10)),
                ('resultado', models.CharField(max_length=255)),
                ('nro_swa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.switchdeacceso')),
                ('nro_swd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.switchdedistribucion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora_ejecucion'],
            },
        ),
        migrations.AddField(
            model_name='historialejecucionswd',
            name='nro_swd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tools.switchdedistribucion'),
            preserve_default=False,
        ),
    ]
