# Generated by Django 4.1.7 on 2023-10-17 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_rack_switchdedistribucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialejecucionswa',
            name='portchannel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historial_portchannel', to='tools.switchdeacceso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialejecucionswa',
            name='nro_swa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_nro_swa', to='tools.switchdeacceso'),
        ),
        migrations.AlterField(
            model_name='historialejecucionswa',
            name='nro_swd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_nro_swd', to='tools.switchdedistribucion'),
        ),
    ]
