# Generated by Django 4.1.7 on 2023-10-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_historialejecucionswa_portchannel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialejecucionswa',
            name='nro_swa',
        ),
    ]
