# Generated by Django 4.1.7 on 2023-10-18 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_remove_historialejecucionswa_nro_swa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialejecucionswa',
            name='nro_swd',
        ),
        migrations.AddField(
            model_name='historialejecucionswa',
            name='nro_rack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historial_nro_rack', to='tools.rack'),
            preserve_default=False,
        ),
    ]
