# Generated by Django 5.1.6 on 2025-04-23 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_remove_historialejecucionswa_nro_swd_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoVLAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=100)),
                ('vlans', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SwitchCore',
            fields=[
                ('nro_swc', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('ip', models.GenericIPAddressField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEjecucionSWCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=10)),
                ('resultado', models.CharField(max_length=255)),
                ('grupo_vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.grupovlan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('switch_core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.switchcore')),
            ],
            options={
                'ordering': ['-fecha_hora_ejecucion'],
            },
        ),
        migrations.AddField(
            model_name='grupovlan',
            name='switch_core',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_vlan', to='tools.switchcore'),
        ),
    ]
