# Generated by Django 5.1.6 on 2025-05-14 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_grupovlan_switchcore_historialejecucionswcore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialejecucionswa',
            name='portchannel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.switchdeacceso'),
        ),
    ]
